version: "3.8"

services:
  
  app:
    build: ./app/
    container_name: app
    ports:
      - 9090:9090
    environment:
      - FIXERIO_ACCESS_KEY=fixeiokey
      - EXCHANGERATESAPIIO_ACCESS_KEY=exchangeratesiokey
      - KEYCLOAK_ADDR=http://keycloak:8080/auth
      - KEYCLOAK_CLIENT_SECRET=na3W0tkdwIBVCen3KCiiuo1xnqkQWl3w
      #- PROFILE=default
      - PROFILE=staging
    command: -Dmaven.test.skip
    depends_on:
      - postgres
      - keycloak
    networks:
      - auth-network
  
  keycloak:
    image: jboss/keycloak:16.1.0
    container_name: keycloak
    ports:
      - 28080:8080
      - 8443:8443
    volumes:
      - ./keycloak/imports:/tmp/keycloak-import
      #- ./keycloak/exports:/tmp/keycloak-export
    environment:
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=123456
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123456
      - JDBC_PARAMS='useSSL=false'
      - PROXY_ADDRESS_FORWARDING=true
      #- KEYCLOAK_LOGLEVEL=TRACE
    #command: [ "-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/tmp/keycloak-export", "-Dkeycloak.migration.usersExportStrategy=SAME_FILE", "-Dkeycloak.migration.realmName=fxrates" ]
    command: [ "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/tmp/keycloak-import", "-Dkeycloak.migration.strategy=IGNORE_EXISTING", "-Dkeycloak.migration.usersExportStrategy=SAME_FILE", "-Dkeycloak.migration.realmName=fxrates", "-Dkeycloak.profile.feature.upload_scripts=enabled" ]
    depends_on:
      - postgres
    networks:
      - auth-network

  postgres:
    image: postgres:alpine3.15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/db-files/
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./keycloak/db/postgres_data:/var/lib/postgresql/data
      - ./keycloak/db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - auth-network

networks:
  auth-network:
  
